# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Deploy HTML a Azure Web App - miwebformulario

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login a Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0C1E74A9364E471A8AE6785160A1739A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B555C2A5D4B848258D9F40AD490BB7C0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_898AAAE2F0C442BCADC279ED31E3973D }}

      - name: Deploy a Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'miwebformulario'
          package: ./public_html
